### ISSUE TITLE
Usage in React Typescript

### ISSUE THREAD

**Issue by coffeeDev98** [justinfagnani/chessboard-element#21]
Hi @justinfagnani ,
Thank you for this element! Have you managed to use it in any React projects or can you guide me on how to make this usable in React projects...?

**Comment by justinfagnani** [comment]
Here's a demo of it in React: https://stackblitz.com/edit/react-chess-board

It's using JS, not TypeScript, but is should still work.

**Comment by coffeeDev98** [comment]
Thanks @justinfagnani ! This helped a lot
