### ISSUE TITLE
404 Error on document link

### ISSUE THREAD

**Issue by pdigre** [justinfagnani/chessboard-element#29]
I have seen the docs earlier, they were good. Please bring them back with the correct link.
[justinfagnani.github.io/chessboard-element/](https://justinfagnani.github.io/chessboard-element/)

**Comment by justinfagnani** [comment]
I don't know what's going on here yet. As far as I know, the pages settings didn't change and the docs/ folder is still checked-in. Looking into it.

**Comment by justinfagnani** [comment]
The site appears to be working again
