### ISSUE TITLE
Usage of fenToObj method

### ISSUE THREAD

**Issue by matsava** [justinfagnani/chessboard-element#3]
Hey there,

I am trying to get the current move in plain text instead of the fen format.

The [docs here](https://justinfagnani.github.io/chessboard-element/docs/#fen_string) mention the use of Chessboard.fenToObj but Chessboard is undefined. 
If I simply import it like this 
```
import * as Chessboard from "chessboard-element";
```
and attempt to use it like this 
```
console.log(Chessboard.fenToObj(value));
```
I am getting the error `Uncaught SyntaxError: Cannot use import statement outside a module`.

Any chance you can guide me on how it should be used?

Thanks for this awesome package!

**EDIT:**
What I am actually looking for is a way to get the actual move when it happens.

```
board.addEventListener('change', (e) => {
        if ('' === game.pgn()) {
            return;
        }

        const {value, oldValue} = e.detail;

       console.log(formatValue(value)); // returns 'd4' or 'd4-d5'
});
```

I am looking for the `formatValue` above

**Comment by matsava** [comment]
I suppose the method is removed in this fork? Is there an alternative?

**Comment by matsava** [comment]
Managed to get the last move from this afterall:
```
game.history({verbose: true})
let lastMove = history[history.length - 1];
```

**Comment by justinfagnani** [comment]
I'm reopening because those docs are wrong and need updating. `Chessboard.fenToObj` doesn't exist, but it is exported from `/lib/chess-utils.js`.

**Comment by justinfagnani** [comment]
Fixed in https://github.com/justinfagnani/chessboard-element/commit/d491a60cc327ac2ae3046dcfd0d03f03781b1251
