### ISSUE TITLE
Occasionally getting a flash of a dragged piece on release.

### ISSUE THREAD

**Issue by benjamind** [justinfagnani/chessboard-element#4]
I'm never going to be able to catch a screenshot of this. But its reproducible on the homepage for me.

* Scroll down to the second example on the homepage (important that the page is scrolled)
* Drag any of the pieces around
* Notice a quick one-frame flash of the piece further up in the page.

Suspect its an offsetting problem since it only happens with page scrolled, in fact the offset of the undesired flash appears to be the same as the scroll offset.

**Comment by justinfagnani** [comment]
Interesting. I've seen this before but inconsistently and didn't track it down yet. Dragged pieces are out of the normal display flow and absolutely positioned, so your suspicion seems likely.

**Comment by justinfagnani** [comment]
Fixed in https://github.com/justinfagnani/chessboard-element/commit/265f6ea215da0f2c49cad9b9c6a3a14419291606
